# Generated by Django 5.0.14 on 2025-10-21 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="classes_can_tutor",
            field=models.TextField(
                blank=True,
                help_text="Classes this TA can tutor (e.g., CSCI 150, CSCI 151)",
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="is_tutor",
            field=models.BooleanField(
                default=False, help_text="Is this user a tutor/TA?"
            ),
        ),
    ]
